/* ============================================
   BastuBazar — Shared Data Store
   ============================================ */

const categories = [
    { image: 'images/cat_agriculture.png', name: 'Agriculture', desc: 'Tractors, tools, irrigation', id: 'cat-agriculture' },
    { image: 'images/cat_realestate.png', name: 'Real Estate', desc: 'Land, plots, rooms', id: 'cat-realestate' },
    { image: 'images/cat_household.png', name: 'Household', desc: 'Furniture, vessels, appliances', id: 'cat-household' },
    { image: 'images/cat_construction.png', name: 'Construction', desc: 'Machinery, scaffolding', id: 'cat-construction' },
    { image: 'images/cat_vehicles.png', name: 'Vehicles', desc: 'Cars, bikes, trucks', id: 'cat-vehicles' },
    { image: 'images/cat_electronics.png', name: 'Electronics', desc: 'Devices, cameras, tools', id: 'cat-electronics' },
    { image: 'images/cat_industrial.svg', name: 'Industrial', desc: 'Generators, compressors', id: 'cat-industrial' },
    { image: 'images/cat_events.svg', name: 'Event Goods', desc: 'Tents, chairs, sound', id: 'cat-events' },
];

const assets = [
    {
        id: 'asset-1',
        title: 'Mahindra 475 Tractor',
        location: 'Chitwan, Nepal',
        category: 'Agriculture',
        tags: ['rent', 'barter', 'sell'],
        price: 'NPR 3,500',
        priceNum: 3500,
        sellPrice: 'NPR 1,500,000',
        period: 'day',
        emoji: '🚜',
        color: '#D1FAE5',
        imageSrc: 'images/tractor_1780417257628.png',
        user: { name: 'Ram Bahadur', initials: 'RB', phone: '9779841234567', rating: 4.8, listings: 12, joined: 'Jan 2025' },
        wishlisted: false,
        description: 'Well-maintained Mahindra 475 DI tractor with 42 HP engine. Perfect for plowing, hauling, and general farming tasks. Comes with standard attachments. Available with or without operator.',
        condition: 'Good',
        postedDate: '2 days ago',
        views: 234,
    },
    {
        id: 'asset-2',
        title: '2 Ropani Land, Flat',
        location: 'Pokhara, Nepal',
        category: 'Real Estate',
        tags: ['rent', 'sell'],
        price: 'NPR 8,000',
        priceNum: 8000,
        sellPrice: 'NPR 25,000,000',
        period: 'month',
        emoji: '🏡',
        color: '#CFFAFE',
        imageSrc: 'images/land_1780417271920.png',
        user: { name: 'Sita Kumari', initials: 'SK', phone: '9779812345678', rating: 4.9, listings: 5, joined: 'Mar 2025' },
        wishlisted: false,
        description: 'Beautiful 2 ropani flat land in Pokhara with stunning mountain views. Located near Lakeside area with road access. Ideal for farming, temporary structures, or long-term lease.',
        condition: 'Excellent',
        postedDate: '5 days ago',
        views: 412,
    },
    {
        id: 'asset-3',
        title: 'Sony A7III Camera Kit',
        location: 'Kathmandu, Nepal',
        category: 'Electronics',
        tags: ['rent', 'barter', 'sell'],
        price: 'NPR 2,000',
        priceNum: 2000,
        sellPrice: 'NPR 180,000',
        period: 'day',
        emoji: '📷',
        color: '#EDE9FE',
        imageSrc: 'images/camera_1780417286385.png',
        user: { name: 'Anil Shrestha', initials: 'AS', phone: '9779823456789', rating: 4.7, listings: 8, joined: 'Feb 2025' },
        wishlisted: false,
        description: 'Sony Alpha A7III full-frame mirrorless camera with 28-70mm kit lens, extra battery, 128GB SD card, and camera bag. Ideal for weddings, events, and professional shoots.',
        condition: 'Like New',
        postedDate: '1 day ago',
        views: 567,
    },
    {
        id: 'asset-4',
        title: 'JCB Excavator 3DX',
        location: 'Biratnagar, Nepal',
        category: 'Construction',
        tags: ['rent'],
        price: 'NPR 12,000',
        priceNum: 12000,
        period: 'day',
        emoji: '🏗️',
        color: '#FEF3C7',
        imageSrc: 'images/excavator_1780417302891.png',
        user: { name: 'Deepak Rai', initials: 'DR', phone: '9779834567890', rating: 4.6, listings: 15, joined: 'Dec 2024' },
        wishlisted: false,
        description: 'JCB 3DX backhoe loader excavator available for daily/weekly rent. Comes with experienced operator. Perfect for construction sites, foundation digging, and earthmoving work.',
        condition: 'Good',
        postedDate: '3 days ago',
        views: 189,
    },
    {
        id: 'asset-5',
        title: 'Wedding Tent Set (50 pax)',
        location: 'Bharatpur, Nepal',
        category: 'Event Goods',
        tags: ['rent', 'barter', 'sell'],
        price: 'NPR 15,000',
        priceNum: 15000,
        sellPrice: 'NPR 85,000',
        period: 'event',
        emoji: '🎪',
        color: '#FCE7F3',
        imageSrc: 'images/tent_1780417316959.png',
        user: { name: 'Gita Maharjan', initials: 'GM', phone: '9779845678901', rating: 4.9, listings: 20, joined: 'Nov 2024' },
        wishlisted: false,
        description: 'Complete wedding tent setup for up to 50 guests. Includes decorated shamiana, 50 chairs, 6 round tables, carpet, lighting, and stage platform. Setup and teardown included in price.',
        condition: 'Excellent',
        postedDate: '1 week ago',
        views: 321,
    },
    {
        id: 'asset-6',
        title: 'Honda Dio Scooter',
        location: 'Lalitpur, Nepal',
        category: 'Vehicles',
        tags: ['rent', 'sell'],
        price: 'NPR 800',
        priceNum: 800,
        sellPrice: 'NPR 120,000',
        period: 'day',
        emoji: '🛵',
        color: '#DBEAFE',
        imageSrc: 'images/scooter_1780417335445.png',
        user: { name: 'Bikash Tamang', initials: 'BT', phone: '9779856789012', rating: 4.5, listings: 3, joined: 'Apr 2025' },
        wishlisted: false,
        description: 'Honda Dio 2022 model scooter in excellent condition. Fuel-efficient and easy to ride. Helmet included. Perfect for daily commuting or exploring the Kathmandu Valley.',
        condition: 'Excellent',
        postedDate: '4 days ago',
        views: 145,
    },
    {
        id: 'asset-7',
        title: '5 KVA Generator',
        location: 'Butwal, Nepal',
        category: 'Industrial',
        tags: ['rent', 'sell'],
        price: 'NPR 1,500',
        priceNum: 1500,
        sellPrice: 'NPR 45,000',
        period: 'day',
        emoji: '⚡',
        color: '#FEF9C3',
        imageSrc: 'images/generator.svg',
        user: { name: 'Suresh Pandey', initials: 'SP', phone: '9779867890123', rating: 4.4, listings: 7, joined: 'Jan 2025' },
        wishlisted: false,
        description: '5 KVA portable diesel generator. Reliable power backup for events, construction sites, or home use during outages. Recently serviced with new oil and filter.',
        condition: 'Good',
        postedDate: '6 days ago',
        views: 98,
    },
    {
        id: 'asset-8',
        title: 'Samsung Washing Machine',
        location: 'Dharan, Nepal',
        category: 'Household',
        tags: ['barter', 'sell'],
        price: 'NPR 18,000',
        priceNum: 18000,
        sellPrice: 'NPR 18,000',
        period: 'one-time',
        emoji: '🧺',
        color: '#E0E7FF',
        imageSrc: 'images/washing_machine.svg',
        user: { name: 'Mina Adhikari', initials: 'MA', phone: '9779878901234', rating: 4.7, listings: 4, joined: 'May 2025' },
        wishlisted: false,
        description: 'Samsung 7kg fully automatic top-load washing machine. 2 years old, working perfectly. Selling because upgrading to a larger model. Willing to barter for a refrigerator or similar.',
        condition: 'Good',
        postedDate: '3 days ago',
        views: 176,
    },
];
